Vagrant.configure("2") do |config|
  ## Chose your base box
  config.vm.box = "DebianWheezy32"

  ## Modify the box
  ## Options here from VBoxManage
  # The SimpleITK build needs a lot of memory, but the machine
  # can be trimmed down after that.
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    # Required for more than one CPU.
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  ## For masterless, mount your salt file root
  salt_file_root = File.expand_path(File.join(File.dirname(__FILE__), '..', 'Salt'))
  config.vm.synced_folder salt_file_root, "/srv"


  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    salt.minion_config = "minion.conf"
    # salt.temp_config_dir = "/existing/folder/on/basebox/"
    # salt.salt_install_type = "git"
    # salt.salt_install_args = "develop"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.minion_key = "salt/key/minion.pem"
    # salt.minion_pub = "salt/key/minion.pub"
  end
end
